### ISSUE TITLE
Does not seem to start

### ISSUE THREAD

**Issue by eplossl** [SNP-MajorK/ED-DataCollector#3]
Tried using it this morning. Found no installer in the package but went ahead and tried running the executable. No window apparently opened and it didn't seem to do anything. Without instructions for use or any readme, it's probably rather difficult to use it.

**Comment by SNP-MajorK** [comment]
Hi, sorry but the description for the Pre-Release is not ready. 
But you have to download the ZIP and extract it. Then Run the eddc.exe which should open an Window. 
There you can go via "Datei" in Codex.
